/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as RecuperacaoRouteImport } from './routes/recuperacao'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EstrategiaRouteImport } from './routes/estrategia'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as BiRouteImport } from './routes/bi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as GestaoCadastroRouteImport } from './routes/gestao.cadastro'
import { Route as BrandPlenNovaRouteImport } from './routes/brand-plen.nova'
import { Route as BrandPlenKitRouteImport } from './routes/brand-plen.kit'
import { Route as BrandPlenHistoricoRouteImport } from './routes/brand-plen.historico'
import { Route as BrandPlenBibliotecaRouteImport } from './routes/brand-plen.biblioteca'
import { Route as ApiTrainingRouteImport } from './routes/api/training'
import { Route as ApiSystemFeedbackRouteImport } from './routes/api/system-feedback'
import { Route as ApiRankingRouteImport } from './routes/api/ranking'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiGrowthRouteImport } from './routes/api/growth'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiBrandLibraryRouteImport } from './routes/api/brand-library'
import { Route as ApiWebhooksMetaLeadsRouteImport } from './routes/api/webhooks/meta-leads'
import { Route as ApiTrainingVideoRouteImport } from './routes/api/training.video'
import { Route as ApiTrainingUploadRouteImport } from './routes/api/training.upload'
import { Route as ApiIntegrationsMetaAdsRouteImport } from './routes/api/integrations/meta-ads'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiGestaoCoursesRouteImport } from './routes/api/gestao/courses'
import { Route as ApiGestaoChannelsRouteImport } from './routes/api/gestao/channels'
import { Route as ApiGestaoAttendancesRouteImport } from './routes/api/gestao/attendances'
import { Route as ApiCrmTransferRouteImport } from './routes/api/crm/transfer'
import { Route as ApiCrmTasksRouteImport } from './routes/api/crm/tasks'
import { Route as ApiCrmLeadsRouteImport } from './routes/api/crm/leads'
import { Route as ApiBrandPlenSettingsRouteImport } from './routes/api/brand-plen.settings'
import { Route as ApiBrandPlenGenerateRouteImport } from './routes/api/brand-plen.generate'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminUnitsRouteImport } from './routes/api/admin/units'
import { Route as ApiGestaoCoursesIdRouteImport } from './routes/api/gestao/courses.$id'
import { Route as ApiGestaoChannelsIdRouteImport } from './routes/api/gestao/channels.$id'
import { Route as ApiCrmLeadsIdRouteImport } from './routes/api/crm/leads.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperacaoRoute = RecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaRoute = EstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoCadastroRoute = GestaoCadastroRouteImport.update({
  id: '/gestao/cadastro',
  path: '/gestao/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPlenNovaRoute = BrandPlenNovaRouteImport.update({
  id: '/brand-plen/nova',
  path: '/brand-plen/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPlenKitRoute = BrandPlenKitRouteImport.update({
  id: '/brand-plen/kit',
  path: '/brand-plen/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPlenHistoricoRoute = BrandPlenHistoricoRouteImport.update({
  id: '/brand-plen/historico',
  path: '/brand-plen/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPlenBibliotecaRoute = BrandPlenBibliotecaRouteImport.update({
  id: '/brand-plen/biblioteca',
  path: '/brand-plen/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainingRoute = ApiTrainingRouteImport.update({
  id: '/api/training',
  path: '/api/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemFeedbackRoute = ApiSystemFeedbackRouteImport.update({
  id: '/api/system-feedback',
  path: '/api/system-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingRoute = ApiRankingRouteImport.update({
  id: '/api/ranking',
  path: '/api/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrowthRoute = ApiGrowthRouteImport.update({
  id: '/api/growth',
  path: '/api/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandLibraryRoute = ApiBrandLibraryRouteImport.update({
  id: '/api/brand-library',
  path: '/api/brand-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaLeadsRoute = ApiWebhooksMetaLeadsRouteImport.update({
  id: '/api/webhooks/meta-leads',
  path: '/api/webhooks/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainingVideoRoute = ApiTrainingVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ApiTrainingRoute,
} as any)
const ApiTrainingUploadRoute = ApiTrainingUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiTrainingRoute,
} as any)
const ApiIntegrationsMetaAdsRoute = ApiIntegrationsMetaAdsRouteImport.update({
  id: '/api/integrations/meta-ads',
  path: '/api/integrations/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCoursesRoute = ApiGestaoCoursesRouteImport.update({
  id: '/api/gestao/courses',
  path: '/api/gestao/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoChannelsRoute = ApiGestaoChannelsRouteImport.update({
  id: '/api/gestao/channels',
  path: '/api/gestao/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoAttendancesRoute = ApiGestaoAttendancesRouteImport.update({
  id: '/api/gestao/attendances',
  path: '/api/gestao/attendances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTransferRoute = ApiCrmTransferRouteImport.update({
  id: '/api/crm/transfer',
  path: '/api/crm/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTasksRoute = ApiCrmTasksRouteImport.update({
  id: '/api/crm/tasks',
  path: '/api/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmLeadsRoute = ApiCrmLeadsRouteImport.update({
  id: '/api/crm/leads',
  path: '/api/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandPlenSettingsRoute = ApiBrandPlenSettingsRouteImport.update({
  id: '/api/brand-plen/settings',
  path: '/api/brand-plen/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandPlenGenerateRoute = ApiBrandPlenGenerateRouteImport.update({
  id: '/api/brand-plen/generate',
  path: '/api/brand-plen/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUnitsRoute = ApiAdminUnitsRouteImport.update({
  id: '/api/admin/units',
  path: '/api/admin/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCoursesIdRoute = ApiGestaoCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoCoursesRoute,
} as any)
const ApiGestaoChannelsIdRoute = ApiGestaoChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoChannelsRoute,
} as any)
const ApiCrmLeadsIdRoute = ApiCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCrmLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/branding': typeof BrandingRoute
  '/conversas': typeof ConversasRoute
  '/crm': typeof CrmRoute
  '/estrategia': typeof EstrategiaRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/brand-library': typeof ApiBrandLibraryRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ranking': typeof ApiRankingRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/brand-plen/biblioteca': typeof BrandPlenBibliotecaRoute
  '/brand-plen/historico': typeof BrandPlenHistoricoRoute
  '/brand-plen/kit': typeof BrandPlenKitRoute
  '/brand-plen/nova': typeof BrandPlenNovaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/brand-plen/generate': typeof ApiBrandPlenGenerateRoute
  '/api/brand-plen/settings': typeof ApiBrandPlenSettingsRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/integrations/meta-ads': typeof ApiIntegrationsMetaAdsRoute
  '/api/training/upload': typeof ApiTrainingUploadRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/branding': typeof BrandingRoute
  '/conversas': typeof ConversasRoute
  '/crm': typeof CrmRoute
  '/estrategia': typeof EstrategiaRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/brand-library': typeof ApiBrandLibraryRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ranking': typeof ApiRankingRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/brand-plen/biblioteca': typeof BrandPlenBibliotecaRoute
  '/brand-plen/historico': typeof BrandPlenHistoricoRoute
  '/brand-plen/kit': typeof BrandPlenKitRoute
  '/brand-plen/nova': typeof BrandPlenNovaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/brand-plen/generate': typeof ApiBrandPlenGenerateRoute
  '/api/brand-plen/settings': typeof ApiBrandPlenSettingsRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/integrations/meta-ads': typeof ApiIntegrationsMetaAdsRoute
  '/api/training/upload': typeof ApiTrainingUploadRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/branding': typeof BrandingRoute
  '/conversas': typeof ConversasRoute
  '/crm': typeof CrmRoute
  '/estrategia': typeof EstrategiaRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/treinamentos': typeof TreinamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/brand-library': typeof ApiBrandLibraryRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ranking': typeof ApiRankingRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/brand-plen/biblioteca': typeof BrandPlenBibliotecaRoute
  '/brand-plen/historico': typeof BrandPlenHistoricoRoute
  '/brand-plen/kit': typeof BrandPlenKitRoute
  '/brand-plen/nova': typeof BrandPlenNovaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/brand-plen/generate': typeof ApiBrandPlenGenerateRoute
  '/api/brand-plen/settings': typeof ApiBrandPlenSettingsRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/integrations/meta-ads': typeof ApiIntegrationsMetaAdsRoute
  '/api/training/upload': typeof ApiTrainingUploadRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bi'
    | '/branding'
    | '/conversas'
    | '/crm'
    | '/estrategia'
    | '/feedback'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/ranking'
    | '/recuperacao'
    | '/treinamentos'
    | '/usuarios'
    | '/api/brand-library'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/profile'
    | '/api/ranking'
    | '/api/system-feedback'
    | '/api/training'
    | '/brand-plen/biblioteca'
    | '/brand-plen/historico'
    | '/brand-plen/kit'
    | '/brand-plen/nova'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/brand-plen/generate'
    | '/api/brand-plen/settings'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/integrations/meta-ads'
    | '/api/training/upload'
    | '/api/training/video'
    | '/api/webhooks/meta-leads'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bi'
    | '/branding'
    | '/conversas'
    | '/crm'
    | '/estrategia'
    | '/feedback'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/ranking'
    | '/recuperacao'
    | '/treinamentos'
    | '/usuarios'
    | '/api/brand-library'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/profile'
    | '/api/ranking'
    | '/api/system-feedback'
    | '/api/training'
    | '/brand-plen/biblioteca'
    | '/brand-plen/historico'
    | '/brand-plen/kit'
    | '/brand-plen/nova'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/brand-plen/generate'
    | '/api/brand-plen/settings'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/integrations/meta-ads'
    | '/api/training/upload'
    | '/api/training/video'
    | '/api/webhooks/meta-leads'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/bi'
    | '/branding'
    | '/conversas'
    | '/crm'
    | '/estrategia'
    | '/feedback'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/ranking'
    | '/recuperacao'
    | '/treinamentos'
    | '/usuarios'
    | '/api/brand-library'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/profile'
    | '/api/ranking'
    | '/api/system-feedback'
    | '/api/training'
    | '/brand-plen/biblioteca'
    | '/brand-plen/historico'
    | '/brand-plen/kit'
    | '/brand-plen/nova'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/brand-plen/generate'
    | '/api/brand-plen/settings'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/integrations/meta-ads'
    | '/api/training/upload'
    | '/api/training/video'
    | '/api/webhooks/meta-leads'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiRoute: typeof BiRoute
  BrandingRoute: typeof BrandingRoute
  ConversasRoute: typeof ConversasRoute
  CrmRoute: typeof CrmRoute
  EstrategiaRoute: typeof EstrategiaRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  MetaAdsRoute: typeof MetaAdsRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  RecuperacaoRoute: typeof RecuperacaoRoute
  TreinamentosRoute: typeof TreinamentosRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiBrandLibraryRoute: typeof ApiBrandLibraryRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiGrowthRoute: typeof ApiGrowthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiRankingRoute: typeof ApiRankingRoute
  ApiSystemFeedbackRoute: typeof ApiSystemFeedbackRoute
  ApiTrainingRoute: typeof ApiTrainingRouteWithChildren
  BrandPlenBibliotecaRoute: typeof BrandPlenBibliotecaRoute
  BrandPlenHistoricoRoute: typeof BrandPlenHistoricoRoute
  BrandPlenKitRoute: typeof BrandPlenKitRoute
  BrandPlenNovaRoute: typeof BrandPlenNovaRoute
  GestaoCadastroRoute: typeof GestaoCadastroRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ApiAdminUnitsRoute: typeof ApiAdminUnitsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiBrandPlenGenerateRoute: typeof ApiBrandPlenGenerateRoute
  ApiBrandPlenSettingsRoute: typeof ApiBrandPlenSettingsRoute
  ApiCrmLeadsRoute: typeof ApiCrmLeadsRouteWithChildren
  ApiCrmTasksRoute: typeof ApiCrmTasksRoute
  ApiCrmTransferRoute: typeof ApiCrmTransferRoute
  ApiGestaoAttendancesRoute: typeof ApiGestaoAttendancesRoute
  ApiGestaoChannelsRoute: typeof ApiGestaoChannelsRouteWithChildren
  ApiGestaoCoursesRoute: typeof ApiGestaoCoursesRouteWithChildren
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  ApiIntegrationsMetaAdsRoute: typeof ApiIntegrationsMetaAdsRoute
  ApiWebhooksMetaLeadsRoute: typeof ApiWebhooksMetaLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperacao': {
      id: '/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof RecuperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia': {
      id: '/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof EstrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/cadastro': {
      id: '/gestao/cadastro'
      path: '/gestao/cadastro'
      fullPath: '/gestao/cadastro'
      preLoaderRoute: typeof GestaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-plen/nova': {
      id: '/brand-plen/nova'
      path: '/brand-plen/nova'
      fullPath: '/brand-plen/nova'
      preLoaderRoute: typeof BrandPlenNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-plen/kit': {
      id: '/brand-plen/kit'
      path: '/brand-plen/kit'
      fullPath: '/brand-plen/kit'
      preLoaderRoute: typeof BrandPlenKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-plen/historico': {
      id: '/brand-plen/historico'
      path: '/brand-plen/historico'
      fullPath: '/brand-plen/historico'
      preLoaderRoute: typeof BrandPlenHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-plen/biblioteca': {
      id: '/brand-plen/biblioteca'
      path: '/brand-plen/biblioteca'
      fullPath: '/brand-plen/biblioteca'
      preLoaderRoute: typeof BrandPlenBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/training': {
      id: '/api/training'
      path: '/api/training'
      fullPath: '/api/training'
      preLoaderRoute: typeof ApiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system-feedback': {
      id: '/api/system-feedback'
      path: '/api/system-feedback'
      fullPath: '/api/system-feedback'
      preLoaderRoute: typeof ApiSystemFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ranking': {
      id: '/api/ranking'
      path: '/api/ranking'
      fullPath: '/api/ranking'
      preLoaderRoute: typeof ApiRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/growth': {
      id: '/api/growth'
      path: '/api/growth'
      fullPath: '/api/growth'
      preLoaderRoute: typeof ApiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-library': {
      id: '/api/brand-library'
      path: '/api/brand-library'
      fullPath: '/api/brand-library'
      preLoaderRoute: typeof ApiBrandLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-leads': {
      id: '/api/webhooks/meta-leads'
      path: '/api/webhooks/meta-leads'
      fullPath: '/api/webhooks/meta-leads'
      preLoaderRoute: typeof ApiWebhooksMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/training/video': {
      id: '/api/training/video'
      path: '/video'
      fullPath: '/api/training/video'
      preLoaderRoute: typeof ApiTrainingVideoRouteImport
      parentRoute: typeof ApiTrainingRoute
    }
    '/api/training/upload': {
      id: '/api/training/upload'
      path: '/upload'
      fullPath: '/api/training/upload'
      preLoaderRoute: typeof ApiTrainingUploadRouteImport
      parentRoute: typeof ApiTrainingRoute
    }
    '/api/integrations/meta-ads': {
      id: '/api/integrations/meta-ads'
      path: '/api/integrations/meta-ads'
      fullPath: '/api/integrations/meta-ads'
      preLoaderRoute: typeof ApiIntegrationsMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/courses': {
      id: '/api/gestao/courses'
      path: '/api/gestao/courses'
      fullPath: '/api/gestao/courses'
      preLoaderRoute: typeof ApiGestaoCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/channels': {
      id: '/api/gestao/channels'
      path: '/api/gestao/channels'
      fullPath: '/api/gestao/channels'
      preLoaderRoute: typeof ApiGestaoChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/attendances': {
      id: '/api/gestao/attendances'
      path: '/api/gestao/attendances'
      fullPath: '/api/gestao/attendances'
      preLoaderRoute: typeof ApiGestaoAttendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/transfer': {
      id: '/api/crm/transfer'
      path: '/api/crm/transfer'
      fullPath: '/api/crm/transfer'
      preLoaderRoute: typeof ApiCrmTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/tasks': {
      id: '/api/crm/tasks'
      path: '/api/crm/tasks'
      fullPath: '/api/crm/tasks'
      preLoaderRoute: typeof ApiCrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/leads': {
      id: '/api/crm/leads'
      path: '/api/crm/leads'
      fullPath: '/api/crm/leads'
      preLoaderRoute: typeof ApiCrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-plen/settings': {
      id: '/api/brand-plen/settings'
      path: '/api/brand-plen/settings'
      fullPath: '/api/brand-plen/settings'
      preLoaderRoute: typeof ApiBrandPlenSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-plen/generate': {
      id: '/api/brand-plen/generate'
      path: '/api/brand-plen/generate'
      fullPath: '/api/brand-plen/generate'
      preLoaderRoute: typeof ApiBrandPlenGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/units': {
      id: '/api/admin/units'
      path: '/api/admin/units'
      fullPath: '/api/admin/units'
      preLoaderRoute: typeof ApiAdminUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/courses/$id': {
      id: '/api/gestao/courses/$id'
      path: '/$id'
      fullPath: '/api/gestao/courses/$id'
      preLoaderRoute: typeof ApiGestaoCoursesIdRouteImport
      parentRoute: typeof ApiGestaoCoursesRoute
    }
    '/api/gestao/channels/$id': {
      id: '/api/gestao/channels/$id'
      path: '/$id'
      fullPath: '/api/gestao/channels/$id'
      preLoaderRoute: typeof ApiGestaoChannelsIdRouteImport
      parentRoute: typeof ApiGestaoChannelsRoute
    }
    '/api/crm/leads/$id': {
      id: '/api/crm/leads/$id'
      path: '/$id'
      fullPath: '/api/crm/leads/$id'
      preLoaderRoute: typeof ApiCrmLeadsIdRouteImport
      parentRoute: typeof ApiCrmLeadsRoute
    }
  }
}

interface ApiTrainingRouteChildren {
  ApiTrainingUploadRoute: typeof ApiTrainingUploadRoute
  ApiTrainingVideoRoute: typeof ApiTrainingVideoRoute
}

const ApiTrainingRouteChildren: ApiTrainingRouteChildren = {
  ApiTrainingUploadRoute: ApiTrainingUploadRoute,
  ApiTrainingVideoRoute: ApiTrainingVideoRoute,
}

const ApiTrainingRouteWithChildren = ApiTrainingRoute._addFileChildren(
  ApiTrainingRouteChildren,
)

interface ApiCrmLeadsRouteChildren {
  ApiCrmLeadsIdRoute: typeof ApiCrmLeadsIdRoute
}

const ApiCrmLeadsRouteChildren: ApiCrmLeadsRouteChildren = {
  ApiCrmLeadsIdRoute: ApiCrmLeadsIdRoute,
}

const ApiCrmLeadsRouteWithChildren = ApiCrmLeadsRoute._addFileChildren(
  ApiCrmLeadsRouteChildren,
)

interface ApiGestaoChannelsRouteChildren {
  ApiGestaoChannelsIdRoute: typeof ApiGestaoChannelsIdRoute
}

const ApiGestaoChannelsRouteChildren: ApiGestaoChannelsRouteChildren = {
  ApiGestaoChannelsIdRoute: ApiGestaoChannelsIdRoute,
}

const ApiGestaoChannelsRouteWithChildren =
  ApiGestaoChannelsRoute._addFileChildren(ApiGestaoChannelsRouteChildren)

interface ApiGestaoCoursesRouteChildren {
  ApiGestaoCoursesIdRoute: typeof ApiGestaoCoursesIdRoute
}

const ApiGestaoCoursesRouteChildren: ApiGestaoCoursesRouteChildren = {
  ApiGestaoCoursesIdRoute: ApiGestaoCoursesIdRoute,
}

const ApiGestaoCoursesRouteWithChildren =
  ApiGestaoCoursesRoute._addFileChildren(ApiGestaoCoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiRoute: BiRoute,
  BrandingRoute: BrandingRoute,
  ConversasRoute: ConversasRoute,
  CrmRoute: CrmRoute,
  EstrategiaRoute: EstrategiaRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  MetaAdsRoute: MetaAdsRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  RecuperacaoRoute: RecuperacaoRoute,
  TreinamentosRoute: TreinamentosRoute,
  UsuariosRoute: UsuariosRoute,
  ApiBrandLibraryRoute: ApiBrandLibraryRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiGrowthRoute: ApiGrowthRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiRankingRoute: ApiRankingRoute,
  ApiSystemFeedbackRoute: ApiSystemFeedbackRoute,
  ApiTrainingRoute: ApiTrainingRouteWithChildren,
  BrandPlenBibliotecaRoute: BrandPlenBibliotecaRoute,
  BrandPlenHistoricoRoute: BrandPlenHistoricoRoute,
  BrandPlenKitRoute: BrandPlenKitRoute,
  BrandPlenNovaRoute: BrandPlenNovaRoute,
  GestaoCadastroRoute: GestaoCadastroRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ApiAdminUnitsRoute: ApiAdminUnitsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiBrandPlenGenerateRoute: ApiBrandPlenGenerateRoute,
  ApiBrandPlenSettingsRoute: ApiBrandPlenSettingsRoute,
  ApiCrmLeadsRoute: ApiCrmLeadsRouteWithChildren,
  ApiCrmTasksRoute: ApiCrmTasksRoute,
  ApiCrmTransferRoute: ApiCrmTransferRoute,
  ApiGestaoAttendancesRoute: ApiGestaoAttendancesRoute,
  ApiGestaoChannelsRoute: ApiGestaoChannelsRouteWithChildren,
  ApiGestaoCoursesRoute: ApiGestaoCoursesRouteWithChildren,
  ApiHealthDbRoute: ApiHealthDbRoute,
  ApiIntegrationsMetaAdsRoute: ApiIntegrationsMetaAdsRoute,
  ApiWebhooksMetaLeadsRoute: ApiWebhooksMetaLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
